title: 
email: 
description:   
domain: wuhsapineen.github.io
baseurl: ""
url: https://wuhsapineen.github.io
markdown: GFM

copyright: [https://creativecommons.org/publicdomain/zero/1.0/, Creative Commons Zero v1.0 Universal]
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed


exclude:
    - .hidden/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/