title: 
email: 
description:   
domain: 
baseurl: wuhsapineen.github.io 
url: https://wuhsapineen.github.io


theme: minima
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/