title: 
email: 
description:   
domain: wuhsapineen.github.io
baseurl: ""
url: https://wuhsapineen.github.io
markdown: kramdown


theme: minima
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/